Pwd
OS-Penguins/seashell pull request #20
Opened 2020-10-24 00:39 UTC by hmontesdeoca

2020-10-24 23:50 UTC, Nicholas-Baron commented on src/pwd.cpp
> +    puts(dir_name);
```suggestion
    const auto * dir_name = get_current_dir_name();
    puts(dir_name);
    free(dir_name);
```
Forgot to free the string.

2020-10-26 16:44 UTC, Nicholas-Baron requested changes

2020-10-26 16:44 UTC, Nicholas-Baron commented on src/pwd.cpp
> +    puts(dir_name);
```suggestion
    auto * dir_name = get_current_dir_name();
    puts(dir_name);
    free(dir_name);
```

2020-10-27 20:30 UTC, Nicholas-Baron approved these changes

2020-10-27 20:31 UTC, jasonling1 approved these changes

2020-10-27 20:53 UTC, merged